version: "3"
services:
  app:
    environment:
      - COMPOSE_PROJECT_NAME=%%%%
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "/app/node_modules"
      - ".:/app"